### PR TITLE
closes #196: Fix Oddly Shaped Counties

### LINKED ISSUE #196: Fix flaw in our KML implementation
Our implementation of counties is flawed.  Some of the weirdly shaped counties had to be commented out to produce legit KML.

This was due to not understanding the full range of KML being used to describe Georgia counties.

### PR DESCRIPTION
**Pull request by RyanBard**
* Fixes buggy data in data.sql.
* Adds more program examples to data.sql to test oddly shaped counties.
* Updates schema.sql to support odd KML shapes.
* Updates County to support storing odd shapes.
* Updates DefaultKmlService to support odd shapes.
* Extracts shape code in DefaultKmlService to DefaultKmlPlacemarkService.
* Adds javadocs explaining empty constructors and setters to Kml objects.
* Creates Kml objects for more complicated shapes.
* Updates unit tests.

### CODE REVIEW

File: src/main/resources/schema.sql [hunk 1]
```diff
@@ -46,7 +46,10 @@ CREATE TABLE county (
     id BIGSERIAL PRIMARY KEY,
```
Comment (RyanBard) [inline src/main/resources/schema.sql]: The counties that are "special":

Brooks - Has 2 Polygons (MultiGeometry)
Lee - Has 2 Polygons (MultiGeometry)
Macon - Has 2 Polygons (MultiGeometry)
Pike - Has a hole (innerBoundaryIs)
Taylor - Has 3 Polygons (MultiGeometry)
Terrell - Has a hole (innerBoundaryIs)
Schley - Has a hole (innerBoundaryIs)
Upson - Has 2 Polygons (MultiGeometry)


Example insert of a "regular" county:

INSERT INTO county (
    name,
    state,
    outer_boundary1,
    inner_boundary1,
    outer_boundary2,
    outer_boundary3
) VALUES (
    'Appling',
    'GA',
    '-82.13584,31.8922 -82.12684,31.89 ...',
    NULL,
    NULL,
    NULL
);


Example insert of a county with a hole:

INSERT INTO county (
    name,
    state,
    outer_boundary1,
    inner_boundary1,
    outer_boundary2,
    outer_boundary3
) VALUES (
    'Pike',
    'GA',
    '-84.53702,33.03646 -84.5276,33.04416 ...',
    '-84.29866,32.99967 -84.29867,33.00414 ...',
    NULL,
    NULL
);


Example insert of a county with 2 polygons:

INSERT INTO county (
    name,
    state,
    outer_boundary1,
    inner_boundary1,
    outer_boundary2,
    outer_boundary3
) VALUES (
    'Brooks',
    'GA',
    '-83.31153,30.63457 -83.31187,30.63459 ...',
    NULL,
    '-83.73743,30.9872 -83.73729,30.99913 ...',
    NULL
);


Example insert of a county with 3 polygons:

INSERT INTO county (
    name,
    state,
    outer_boundary1,
    inner_boundary1,
    outer_boundary2,
    outer_boundary3
) VALUES (
    'Taylor',
    'GA',
    '-84.05152,32.52205 -84.05136,32.52205 ...',
    NULL,
    '-84.37282,32.39755 -84.37236,32.39755 ...',
    '-84.45156,32.54235 -84.4441,32.55485 ...'
);
